version: '3.5'

services:
  jupyterhub:
    build: jupyterhub
    image: local/jupyterhub
    container_name: jupyterhub
    ports:
      - "8000:8000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /etc/passwd:/etc/passwd:ro
      - /etc/shadow:/etc/shadow:ro
    environment:
      - DOCKER_JUPYTER_CONTAINER=${DOCKER_JUPYTER_CONTAINER}
      - HOST_DATA_PATH=${HOST_DATA_PATH}
      - DOCKER_NETWORK_NAME=${DOCKER_NETWORK_NAME}
      - ADMIN_USER=${ADMIN_USER}
    networks:
      - jupyterhub
    restart: always

  datascience-notebook:
    build: datascience-notebook
    image: local/datascience-notebook
    network_mode: none
    command: echo

networks:
  jupyterhub:
    name: ${DOCKER_NETWORK_NAME}
    driver: bridge
